gpt4:
  prompt_template: "triviaqa_gpt4/basic_prompt.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "gpt-4-0613"
    max_tokens: 50
    temperature: 0
  completion_parser_kwargs:
    outputs_to_match:
      1: '(?:^|\n) ?Correct \(Y\)?'
      2: '(?:^|\n) ?NotCorrect \(N\)'
  batch_size: 1
